global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bitcoin-lstm-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'bitcoin-lstm-api'
    static_configs:
      - targets: ['bitcoin-lstm-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
